import React, { useState, useEffect } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { GlassCard } from '@/components/ui/GlassCard';
import { Sparkles, ChevronDown, ChevronUp, Bot, ArrowRight, Activity, TrendingUp, Loader2, FileCheck2, Globe } from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from "@/components/ui/select";
import { analyzeMedicalTextAction, seedVitalsAction, translateTextAction, generateHealthScoreAction } from '@/app/actions';
import { motion, AnimatePresence } from 'framer-motion';
import { supabase } from '@/lib/supabase/supabaseClient';
import { useAuth } from '@/context/AuthContext';
import { LoadingSpinner } from '@/components/ui/LoadingSpinner';
import { toast } from 'sonner';

interface HealthInsightPanelProps {
    onHealthScoreUpdate?: (score: number) => void;
    initialScore?: number | null;
}

export function HealthInsightPanel({ onHealthScoreUpdate, initialScore }: HealthInsightPanelProps) {
    const { user } = useAuth();
    const [isExpanded, setIsExpanded] = useState(false);
    const [insight, setInsight] = useState<string | null>(null);
    const [healthScore, setHealthScore] = useState<number | null>(initialScore || null);
    const [vitalsAnalysis, setVitalsAnalysis] = useState<string | null>(null);
    const [loading, setLoading] = useState(false);
    const [seeding, setSeeding] = useState(false);
    const [language, setLanguage] = useState("English");
    const [stats, setStats] = useState({
        recordCount: 0,
        appointmentCount: 0,
        hasVitals: false,
        lastVitalDate: null as string | null
    });
    const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
    const [isTranslating, setIsTranslating] = useState(false);
    const [originalInsight, setOriginalInsight] = useState<string | null>(null);

    useEffect(() => {
        if (initialScore) {
            setHealthScore(initialScore);
        }
    }, [initialScore]);

    useEffect(() => {
        const fetchStats = async () => {
            if (!user) return;

            console.log('Fetching medical records for user:', user.id);

            const { count: recordCount, error: recordError } = await supabase
                .from('medical_records')
                .select('*', { count: 'exact', head: true })
                .eq('user_id', user.id);

            console.log('Medical records result:', { recordCount, recordError });

            const { count: aptCount } = await supabase
                .from('appointments')
                .select('*', { count: 'exact', head: true })
                .eq('patient_id', user.id)
                .in('status', ['completed', 'confirmed']);

            // Generate a simple "Profile Completeness" or Activity score
            setStats({
                recordCount: recordCount || 0,
                appointmentCount: aptCount || 0,
                hasVitals: (recordCount || 0) > 0,
                lastVitalDate: null // We could fetch this if needed
            });
        };

        fetchStats();
    }, [user]);

    // Auto-generate insight if we have records but no score, and haven't generated yet
    useEffect(() => {
        if (stats.recordCount > 0 && healthScore === null && !loading && !hasAutoGenerated && !insight) {
            console.log("Auto-generating health insight...");
            setHasAutoGenerated(true);
            generateInsight(true); // pass true for "silent" or "auto" mode if needed, for now just call it
        }
    }, [stats.recordCount, healthScore, loading, hasAutoGenerated, insight]);

    // Auto-translate insight when language changes
    useEffect(() => {
        const translateInsight = async () => {
            // Only translate if we have an insight and language is not English
            if (!originalInsight && insight && language !== "English") {
                // Store the original English insight
                setOriginalInsight(insight);
            }

            const textToTranslate = originalInsight || insight;

            if (!textToTranslate || language === "English") {
                // Reset to original if switching back to English
                if (language === "English" && originalInsight) {
                    setInsight(originalInsight);
                }
                return;
            }

            setIsTranslating(true);
            try {
                const translated = await translateTextAction(textToTranslate, language);
                if (translated) {
                    setInsight(translated);
                }
            } catch (error) {
                console.error("Translation error:", error);
                toast.error("Failed to translate insights");
            } finally {
                setIsTranslating(false);
            }
        };

        if (insight) {
            translateInsight();
        }
    }, [language]);

    const generateInsight = async (isAuto = false) => {
        setLoading(true);
        try {
            if (!user) return;

            // Use the new structured action
            const resultString = await generateHealthScoreAction(user.id, language);

            if (!resultString) throw new Error("No insight generated");

            let parsedResult;
            try {
                parsedResult = JSON.parse(resultString);
            } catch (e) {
                console.error("Error parsing result:", e);
                // Fallback
                parsedResult = {
                    score: null,
                    analysis: resultString,
                    summary: '',
                    vitals_analysis: null
                };
            }

            const insightText = parsedResult.analysis || parsedResult.summary;
            setInsight(insightText);
            setOriginalInsight(insightText); // Store the original English version
            setHealthScore(parsedResult.score);
            setVitalsAnalysis(parsedResult.vitals_analysis);
            if (!isAuto) setIsExpanded(true); // Don't auto-expand on load

            // Notify parent if score is available
            if (typeof parsedResult.score === 'number' && onHealthScoreUpdate) {
                onHealthScoreUpdate(parsedResult.score);
            }

            if (!isAuto) toast.success("Health analysis generated successfully");
        } catch (error) {
            console.error("Insight generation error:", error);
            if (!isAuto) toast.error("Failed to generate health insights. Please try again.");
        } finally {
            setLoading(false);
        }
    };

    const handleSeedVitals = async () => {
        if (!user) return;
        setSeeding(true);
        try {
            const result = await seedVitalsAction(user.id);
            if (result.success) {
                toast.success(result.message);
                // Refresh stats
                setStats(prev => ({ ...prev, recordCount: prev.recordCount + 2, hasVitals: true }));
            } else {
                toast.error(result.message);
            }
        } catch (error) {
            console.error("Seeding error:", error);
            toast.error("Failed to seed vitals");
        } finally {
            setSeeding(false);
        }
    };

    return (
        <GlassCard className="relative overflow-hidden p-6">
            {/* AI Glow Effect */}
            <div className="absolute -top-10 -right-10 h-40 w-40 rounded-full bg-indigo-500/10 dark:bg-indigo-500/5 blur-2xl group-hover:bg-indigo-500/20 transition-colors duration-500" />

            <div className="relative z-10">
                {/* Header Row - Title */}
                <div className="flex items-start gap-3 mb-4">
                    <div className="p-2.5 rounded-xl bg-gradient-to-br from-indigo-500 to-purple-600 text-white shadow-lg shadow-indigo-500/20 dark:shadow-indigo-500/10 shrink-0">
                        <Bot className="h-5 w-5" />
                    </div>
                    <div className="min-w-0 flex-1">
                        <div className="flex items-center gap-2 flex-wrap">
                            <h3 className="font-bold text-slate-800 dark:text-white text-lg leading-none">Health AI</h3>
                            <span className="text-[10px] font-semibold text-white bg-gradient-to-r from-indigo-500 to-purple-600 px-2 py-0.5 rounded-full shadow-sm whitespace-nowrap">Powered by Sarvam</span>
                        </div>
                        <span className="text-[10px] uppercase font-bold tracking-wider text-indigo-500 dark:text-indigo-400 mt-1 block">Insights & Trends</span>
                    </div>
                </div>

                {/* Records Count + Language Selector - Below Header */}
                <div className="flex items-center justify-between mb-4">
                    {/* Activity Pill */}
                    <div className="flex items-center gap-2 bg-white/60 dark:bg-white/5 backdrop-blur-sm border border-indigo-100 dark:border-indigo-500/20 rounded-full pl-1 pr-3 py-1">
                        <div className="h-6 w-6 rounded-full bg-emerald-500 flex items-center justify-center text-[10px] font-bold text-white shadow-sm">
                            <FileCheck2 className="h-3 w-3" />
                        </div>
                        <span className="text-xs font-medium text-slate-600 dark:text-slate-300">{stats.recordCount} Records</span>
                    </div>

                    {/* Language Selector */}
                    <Select value={language} onValueChange={setLanguage} disabled={isTranslating}>
                        <SelectTrigger className="w-[130px] h-8 bg-white/60 dark:bg-white/5 border-indigo-100 dark:border-indigo-500/20 text-xs font-medium text-slate-600 dark:text-slate-300">
                            {isTranslating ? (
                                <Loader2 className="w-3 h-3 mr-2 text-indigo-500 animate-spin" />
                            ) : (
                                <Globe className="w-3 h-3 mr-2 text-indigo-500" />
                            )}
                            <SelectValue placeholder="Language" />
                        </SelectTrigger>
                        <SelectContent align="end">
                            <SelectItem value="English">English</SelectItem>
                            <SelectItem value="Hindi">Hindi (हिंदी)</SelectItem>
                            <SelectItem value="Bengali">Bengali (বাংলা)</SelectItem>
                            <SelectItem value="Gujarati">Gujarati (ગુજરાતી)</SelectItem>
                            <SelectItem value="Kannada">Kannada (ಕನ್ನಡ)</SelectItem>
                            <SelectItem value="Malayalam">Malayalam (മലയാളം)</SelectItem>
                            <SelectItem value="Marathi">Marathi (मराठी)</SelectItem>
                            <SelectItem value="Oriya">Oriya (ଓଡ଼ିଆ)</SelectItem>
                            <SelectItem value="Punjabi">Punjabi (ਪੰਜਾਬੀ)</SelectItem>
                            <SelectItem value="Tamil">Tamil (தமிழ்)</SelectItem>
                            <SelectItem value="Telugu">Telugu (తెలుగు)</SelectItem>
                        </SelectContent>
                    </Select>
                </div>

                {/* Health Score Display (if available) */}
                {healthScore !== null && (
                    <div className="flex flex-col items-center justify-center mb-4">
                        <div className="relative flex items-center justify-center w-12 h-12">
                            <svg className="w-full h-full transform -rotate-90">
                                <circle
                                    cx="24"
                                    cy="24"
                                    r="20"
                                    stroke="currentColor"
                                    strokeWidth="4"
                                    fill="transparent"
                                    className="text-indigo-100"
                                />
                                <circle
                                    cx="24"
                                    cy="24"
                                    r="20"
                                    stroke="currentColor"
                                    strokeWidth="4"
                                    fill="transparent"
                                    strokeDasharray={125.6}
                                    strokeDashoffset={125.6 - (125.6 * healthScore) / 100}
                                    className={`text-indigo-500 transition-all duration-1000 ease-out`}
                                />
                            </svg>
                            <span className="absolute text-xs font-bold text-slate-700 dark:text-white">{healthScore}</span>
                        </div>
                        <span className="text-[10px] font-medium text-slate-400 dark:text-slate-500 mt-1">Health Score</span>
                    </div>
                )}
            </div>

            <div className="space-y-4">
                {!insight ? (
                    <div className="bg-white/50 dark:bg-white/5 rounded-xl p-4 border border-indigo-50 dark:border-indigo-500/10 text-center">
                        <Activity className="h-8 w-8 text-indigo-300 dark:text-indigo-500/50 mx-auto mb-2 opacity-50" />
                        <p className="text-sm text-slate-600 dark:text-slate-300 font-medium">Ready to analyze your records</p>
                        <p className="text-xs text-slate-400 mt-1">
                            {stats.recordCount > 0
                                ? `AI will analyze your ${stats.recordCount} medical records.`
                                : "Upload records to get personalized insights."}
                        </p>
                    </div>
                ) : (
                    <div className="flex items-start gap-4 p-3 bg-indigo-50/50 dark:bg-indigo-500/10 rounded-lg">
                        <Sparkles className="h-5 w-5 text-indigo-500 dark:text-indigo-400 mt-0.5 shrink-0 animate-pulse" />
                        <p className="text-sm font-medium text-slate-700 dark:text-slate-200">Analysis ready. Review your personalized health summary below.</p>
                    </div>
                )}

                <AnimatePresence>
                    {isExpanded && insight && (
                        <motion.div
                            initial={{ height: 0, opacity: 0 }}
                            animate={{ height: 'auto', opacity: 1 }}
                            exit={{ height: 0, opacity: 0 }}
                            className="overflow-hidden"
                        >
                            <div className="p-5 rounded-xl bg-white/60 dark:bg-white/5 border border-indigo-100 dark:border-indigo-500/10 text-sm text-slate-700 dark:text-slate-300 leading-relaxed shadow-inner dark:shadow-none markdown-content">
                                <ReactMarkdown
                                    remarkPlugins={[remarkGfm]}
                                    components={{
                                        ul: ({ ...props }) => <ul className="list-disc pl-4 my-2 space-y-1 marker:text-indigo-500" {...props} />,
                                        ol: ({ ...props }) => <ol className="list-decimal pl-4 my-2 space-y-1 marker:text-indigo-500" {...props} />,
                                        li: ({ ...props }) => <li className="pl-1" {...props} />,
                                        p: ({ ...props }) => <p className="mb-2 last:mb-0" {...props} />,
                                        strong: ({ ...props }) => <strong className="font-bold text-slate-900" {...props} />,
                                        h1: ({ ...props }) => <h1 className="text-base font-bold mb-2 mt-3 text-slate-900" {...props} />,
                                        h2: ({ ...props }) => <h2 className="text-sm font-bold mb-1.5 mt-2 text-slate-800" {...props} />,
                                        h3: ({ ...props }) => <h3 className="text-sm font-semibold mb-1 mt-2 text-slate-700" {...props} />,
                                    }}
                                >
                                    {insight}
                                </ReactMarkdown>
                                <div className="mt-4 pt-4 border-t border-indigo-100 flex items-center gap-2 text-xs text-slate-400">
                                    <Bot className="h-3 w-3" />
                                    <span>AI-generated analysis based on your records. Consult a doctor for diagnosis.</span>
                                </div>
                            </div>
                        </motion.div>
                    )}
                </AnimatePresence>

                <Button
                    onClick={insight ? () => setIsExpanded(!isExpanded) : () => generateInsight(false)}
                    className="w-full justify-between bg-white dark:bg-white/5 hover:bg-indigo-50 dark:hover:bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 border border-indigo-200 dark:border-indigo-500/20 hover:border-indigo-300 dark:hover:border-indigo-500/30 shadow-sm h-12 rounded-xl group transition-all"
                    disabled={loading || stats.recordCount === 0}
                >
                    <span className="font-semibold">
                        {loading ? 'Analyzing Health Data...' : (insight ? (isExpanded ? 'Hide Analysis' : 'Read Full Analysis') : 'Generate Health Report')}
                    </span>
                    {insight && (isExpanded ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />)}
                    {!insight && !loading && <ArrowRight className="h-4 w-4 group-hover:translate-x-1 transition-transform" />}
                    {loading && <LoadingSpinner size={16} className="text-white" />}
                </Button>

                {stats.recordCount === 0 && (
                    <div className="flex flex-col gap-2 items-center">
                        <p className="text-[10px] text-center text-amber-500">
                            Upload a medical record first to generate insights.
                        </p>
                        <Button variant="outline" size="sm" onClick={handleSeedVitals} disabled={seeding} className="text-xs h-7">
                            {seeding ? <Loader2 className="w-3 h-3 animate-spin mr-1" /> : <Activity className="w-3 h-3 mr-1" />}
                            Add Demo Vitals
                        </Button>
                    </div>
                )}
            </div>
        </GlassCard >
    );
}
